language: node_js
sudo: false
node_js:
  - "12"

install:
  - npm install

script:
  - mkdir deploy
  - cp index.html deploy
  - cp index.js deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: deploy
